### ISSUE TITLE
I think xdebug detection isn't working

### ISSUE THREAD

**Issue by nickchomey** [rusoft/php-simple-benchmark-script#15]
I just downloaded v 1.0.41 and ran it on the same server that I had run 1.0.39 and the scores were about 2x slower. I thought that perhaps you changed the tests, so looked at the code here and saw that you only really added some checks for xdebug, opcache etc...

I had installed xdebug a few days ago and set it to only be used on trigger mode. But I disabled xdebug anyway and the test scores were back to the previous speed.

So, it would seem that xdebug is slowing it down by 2x, yet the benchmark output said "xdebug : no". Also, I see in the code that it is supposed to print a message for xdebug, opcache etc... and even though it says "opcache : yes", the message wasn't printed. 

Please let me know if you need any other information to debug this. 

Thanks!

**Comment by sergey-dryabzhinsky** [comment]
I fix xdebug detection in 1.0.43, I hope.

**Comment by sergey-dryabzhinsky** [comment]
@nickchomey Do you test it with latest 1.0.46 version?

**Comment by nickchomey** [comment]
Hi there, sorry I didn't reply previously. I just downloaded the benchmark and it looks like it properly detects and warns about xdebug. Disabling xdebug dropped the total time from 175 to 76 seconds.

**Comment by sergey-dryabzhinsky** [comment]
I think I know what did you want from script.
It should not drop execution but warn about xdebug.
And try to show some results until execution time is over.

**Comment by sergey-dryabzhinsky** [comment]
It's like set option `xdebug.mode` to `off` is the deal.

**Comment by nickchomey** [comment]
To clarify, I think everything is fine with the script now! It notifies/warns you if xdebug is enabled on the server so that you can turn it off. 

I don't think there is anything else that you need to change regarding xdebug!

**Comment by sergey-dryabzhinsky** [comment]
Ok. I'll still have some ideas about xdebug.
New version will be out very soon.
