### ISSUE TITLE
timeweb

### ISSUE THREAD

**Issue by Alexufo** [rusoft/php-simple-benchmark-script#2]
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 98566168 bytes) in  public_html/bench.php on line 217

timeweb.ru вирт тариф

**Comment by sergey-dryabzhinsky** [comment]
Для корректной рабоыт скрипта сейчас нужно 256Мб и более.

В ближайшем будущем попробуем делать перерасчеты максимальных размеров массивов в зависимости от кол-ва доступной памяти.

**Comment by sergey-dryabzhinsky** [comment]
Попробуйте последню версию 1.0.14.

**Comment by Alexufo** [comment]
Там лимит в 128MB но все равно скрипт больше 30 сек работает и его грохают, если не тариф битрикса. На fornex.com отрабатывает на тарифе дешевом полностью, но он таймвебу в подметки не годится по скорости.

**Comment by sergey-dryabzhinsky** [comment]
Да, скрипт может работать более 2 минут.

Его убивает сам php? Или система на хостинге?
Запускаете из консоли или через apache?

**Comment by Alexufo** [comment]
Это частое ограничения хостингов в 30 сек на лимит выполнения времени скрипта. Запускаю через апач, кидаю на хистинг и вызываю браузером. Могу сделать и по SSH но... смысл немножко не в этом.

**Comment by sergey-dryabzhinsky** [comment]
Тут уже сложнее.
php-4 работает в 2 раза медленее php-5, и в 4-5 раз медленее php-7.
Плюс на разных хостингах разные по скорости процессоры.

Сейчас проще будет запустить по ssh.

**Comment by sergey-dryabzhinsky** [comment]
Можно попробовать передавать максимальное кол-во операций во всех тестах.
Через GET/POST/argv/getenv.

Я попробую что-нибудь придумать.

**Comment by ryr** [comment]
последняя версия не работает в php 7.1, выдает
PHP Fatal error: Allowed memory size...
открыл пул https://github.com/rusoft/php-simple-benchmark-script/pull/4
не уверен ошибка ли это в php 7 или так и задумано

**Comment by sergey-dryabzhinsky** [comment]
@ryr перенес в #5

**Comment by sergey-dryabzhinsky** [comment]
Можно попробовать новую версию 1.0.17

**Comment by Alexufo** [comment]
работает если до таких лимитов опустить, иначе 502 , которая даж в error.log не отмечается.

![screenshot_24](https://cloud.githubusercontent.com/assets/1562329/26194298/9f320300-3bc0-11e7-9433-c1a5325a09c3.jpg)

**Comment by sergey-dryabzhinsky** [comment]
502 - это вероятно уже отваливается nginx.
Если есть возможность - проверьте настройки nginx: proxy_send_timeout, proxy_read_timeout.

Можно попробовать дать возможность передавать значения для настроек memory_limit и max_execution_time через GET-параметры запроса.

**Comment by sergey-dryabzhinsky** [comment]
Можно попробовать новую версию 1.0.18.
Вызывать так: http://www.example.com/bench.php?time_limit=10

**Comment by sergey-dryabzhinsky** [comment]
Так же на timeweb веселые ограничения: https://timeweb.com/ru/services/hosting/rules/
Пункты 2.2.2 и 2.3.2

**Comment by Alexufo** [comment]
Это типичные ограничения, которые просто открыто прописаны в отличие от многих других хостингов. Скрипты по времени рубят почти все. Да, работает с лимитом. Мне кажется он дожен быть по дефолту, а параметры для более серьезных проектов.


![screenshot_28](https://cloud.githubusercontent.com/assets/1562329/26221855/99039790-3c20-11e7-9a3a-1999afd1ff36.jpg)
.

**Comment by sergey-dryabzhinsky** [comment]
> Мне кажется он должен быть по дефолту, а параметры для более серьезных проектов.
Увы, на разный хостингах - разные настройки.
На НИКе, например, всё работает без ограничения по времени, со значениями по-умолчанию.
Так что лучше не затачивать его под TimeWeb.

Плюс, изначально скрипт был сделан только для запуска из консоли.

С одним файлом попробую еще раз сделать.

**Comment by sergey-dryabzhinsky** [comment]
А попробуйте сейчас версию 1.0.19 - может быть принудительно устанавливать time_limit больше не нужно.
Теперь вывод должен происходить без буферизации.
nginx возможно не будет обрывать соединнение с apache.
Ну или лимит можно будет поднять больше 10 секунд.

**Comment by Alexufo** [comment]
Доживает до 07_1_hashing  и процесс Killed судя по ответу консоли  :-)

**Comment by sergey-dryabzhinsky** [comment]
Печаль. Жестокий timeweb.

**Comment by sergey-dryabzhinsky** [comment]
Есть безумный вариант сделать работу скрипта, как выгрузки в bitrix, например.
Т.е. сделать отработку по шагам по ХХсекунд, пока все тесты не выполнятся.

**Comment by Alexufo** [comment]
Разбить по блокам и дергать аяксом? Да ну, как то усложняет все. Тестирование имеет смысл для сравнения. Мне было интересно найти забугорный хостинг с аналогичными таймвебовскими параметрами, так как скорость его устраивает в отличие от форнекса, потому что по другим параметрам проверить обьективно как-то не могу В свое время пользовал .php-benchmark-script.com но сейчас он помер.
вот тут делятся результатами https://www.lowendtalk.com/discussion/59530/php-benchmark-script

У вас набор мощнее конечно. Но выходи тест за 30 секунд.

**Comment by sergey-dryabzhinsky** [comment]
Нам (@rusoft) было интересно сравнивать скорость работы разных версий пхп на одном сервере.
Чтобы было чем аргументировать клиентам обновление движков, переход на новые версии php ;).
Ну и сами сервера тоже интересно сравнивать.

**Comment by sergey-dryabzhinsky** [comment]
Плюс было полезно для разработчиков выяснить, как разные конструкции в языке влияют на производительность кода.

Например:
- срачи по поводу скорости работы строк `'a'`  и `"a"` были важны до выхода 5.0+.
Если в 4.4 двухкавычные строки работали медленнее, то в 5.0+ - уже могут быть и быстрее.
- обращение к несуществующим переменным, константам, ключам массива в 5-10 раз медленнее обращения к существующим.
- код с `try {} catch` - может работать медленнее в 4 раза, чем без него.

**Comment by sergey-dryabzhinsky** [comment]
Я думаю, что уже ничего нового для TimeWeb не придумаешь.

Можно закрывать задачу? Или есть еще идеи?

**Comment by sergey-dryabzhinsky** [comment]
Закрываю.
