### ISSUE TITLE
GD2 and ImageMagick benchmarks

### ISSUE THREAD

**Issue by kanevbg** [rusoft/php-simple-benchmark-script#23]
GD2 and ImageMagick benchmarks when the corresponding extension is loaded.

Only with in-memory operations not related to accessing file system.

**Comment by sergey-dryabzhinsky** [comment]
Probably draw simple qrcode with big square pixels

**Comment by kanevbg** [comment]
I like your idea.
And to note that in addition to ImageMagick an GraphicMagick benchmark can be supported with the same tests created for ImageMagick as the extensions PHP API is said to be the same.

**Comment by sergey-dryabzhinsky** [comment]
unfortunaely all versions of imagick module breake down php process. so I can't test my code for a some time

**Comment by sergey-dryabzhinsky** [comment]
Run imagick via stock php + md-imafick. Done in version 1.0.57
